FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# totem-config-service

Provides simple RESTFul service for creating, modifying and accessing JSON/Yaml configuration files in different sources.

## Root Collection [/]
### Root API [GET]

+ Request

    + Headers

            Accept: application/vnd.totem-config-service.root.v1+json

+ Response 200 (application/vnd.totem-config-service.root.v1+json)

    + Headers

            Link: <http://localhost:9003/schemas/root-v1#>; rel="describedBy"
            
    + Body

            {
                "version": "0.0.1"
            }
    
    + Schema
            
            {
                "$ref": "https://raw.githubusercontent.com/totem/config/feature_parent-config/schemas/root-v1.json"
            }
